name: MS Teams Deploy Card

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./
        if: always()
        with:
          github_context: ${{ toJson(github) }}
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          show-on-start: false
          show-on-exit: true
          card-layout-exit: changelog
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          timezone: Australia/Brisbane
